## 라이브러리 불러오기 및 폰트 설정
- Numpy(Numerical Python)
    - 파이썬에서 과학적 계산을 위한 핵심 라이브러리
    - 다차원 배열 객체(ndarray)와 배열과 함께 작동하는 도구들을 제공
    - 다차원 행렬 자료구조인 ndarray를 통해 벡터 및 행렬을 사용하는 선형 대수 계산에서 주로 사용
    - Numpy는 편의성 뿐만 아니라, 속도면에서도 순수 파이썬에 비해 압도적으로 빠름

In [46]:
#라이브러리 로드
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 

%matplotlib inline

In [47]:
plt.rc("font", family="Malgun Gothic")
#마이너스 폰트 깨지는 문제에 대한 대처          
plt.rc("axes", unicode_minus=False)

In [48]:
#레티나 설정을 해주면 글씨가 좀 더 선명하게 보입니다.
#폰트의 주변이 흐릿하게 보이는 것을 방지합니다.
%config InlineBackend.figure_format = 'retina'

In [49]:
# 한글폰트 사용을 위해 설치
# 아래 모듈을 설치하고 불러오면 별도의 한글폰트 설정이 필요 없습니다.
!pip install koreanize-matplotlib

import koreanize_matplotlib

Requirement already satisfied: koreanize-matplotlib in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (0.1.1)
Requirement already satisfied: matplotlib in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from koreanize-matplotlib) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->koreanize-matplotlib) (1.0.7)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->koreanize-matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->koreanize-matplotlib) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->koreanize-matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.20 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->koreanize-matplotlib) (1.24.3)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->koreanize-matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->koreanize-matplotlib) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->koreanize-matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->koreanize-matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib->koreanize-matplotlib) (1.16.0)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## 데이터 불러오기

In [50]:
df = pd.read_csv("data/dtg_01_1101.csv") #encoding = "cp949"를 통해 한글 폰트를 에러 없이 가져올 수 있음.
df.shape #이렇게 양이 많은 데이터를 엑셀로 분석한다면 매우 느리고 에러가 발생할 수 있기 때문에 판다스가 유용하다.

(28538, 32)

In [51]:
df.head(3)

,단말ID,차대번호,트립시작일,정보발생일,누적주행거리,일일주행거리,차량속도,RPM,브레이크상태,차량위치X,...,운전자코드,메시지생성일자,메시지생성시간,응답코드,데이터길이,수집유형,DTG정보수,차량코드,차량번호,Column1
0,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:11:48,1045469,0,0,125,1,0,...,9179345,2022-11-01,91245,0,4924,C,60,15,충남72아3043,NaN
1,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:11:51,1045469,0,0,275,0,0,...,9179345,2022-11-01,91245,0,4924,C,60,15,충남72아3043,NaN
2,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:11:52,1045469,0,0,665,0,0,...,9179345,2022-11-01,91245,0,4924,C,60,15,충남72아3043,NaN

## 기본 정보 보기

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28538 entries, 0 to 28537
Data columns (total 32 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   단말ID     28538 non-null  int64
 1   차대번호     28538 non-null  object
 2   트립시작일    28538 non-null  object
 3   정보발생일    28538 non-null  object
 4   누적주행거리   28538 non-null  int64
 5   일일주행거리   28538 non-null  int64
 6   차량속도     28538 non-null  int64
 7   RPM      28538 non-null  int64
 8   브레이크상태   28538 non-null  int64
 9   차량위치X    28538 non-null  int64
 10  차량위치Y    28538 non-null  int64
 11  기기상태     28538 non-null  int64
 12  일일연료사용량  28538 non-null  int64
 13  누적연료사용량  28538 non-null  int64
 14  배터리전압    28538 non-null  int64
 15  일련번호     28538 non-null  int64
 16  방위각      28538 non-null  int64
 17  가속도X     28538 non-null  int64
 18  가속도Y     28538 non-null  int64
 19  메세지코드    28538 non-null  int64
 20  기기모델     28538 non-null  object
 21  사업자번호    28538 non-null  int64
 22  운전자코드    28538 non-null  int64
 23  메시지생성일자  28538 non-null  object
 24  메시지생성시간  28538 non-null  int64
 25  응답코드     28538 non-null  int64
 26  데이터길이    28538 non-null  int64
 27  수집유형     28538 non-null  object
 28  DTG정보수   28538 non-null  int64
 29  차량코드     28538 non-null  int64
 30  차량번호     28538 non-null  object
 31  Column1  0 non-null      float64
dtypes: float64(1), int64(24), object(7)
memory usage: 7.0+ MB

In [53]:
df.columns

Index(['단말ID', '차대번호', '트립시작일', '정보발생일', '누적주행거리', '일일주행거리', '차량속도', 'RPM',
       '브레이크상태', '차량위치X', '차량위치Y', '기기상태', '일일연료사용량', '누적연료사용량', '배터리전압',
       '일련번호', '방위각', '가속도X', '가속도Y', '메세지코드', '기기모델', '사업자번호', '운전자코드',
       '메시지생성일자', '메시지생성시간', '응답코드', '데이터길이', '수집유형', 'DTG정보수', '차량코드', '차량번호',
       'Column1'],
      dtype='object')

In [54]:
df.dtypes

단말ID         int64
차대번호        object
트립시작일       object
정보발생일       object
누적주행거리       int64
일일주행거리       int64
차량속도         int64
RPM          int64
브레이크상태       int64
차량위치X        int64
차량위치Y        int64
기기상태         int64
일일연료사용량      int64
누적연료사용량      int64
배터리전압        int64
일련번호         int64
방위각          int64
가속도X         int64
가속도Y         int64
메세지코드        int64
기기모델        object
사업자번호        int64
운전자코드        int64
메시지생성일자     object
메시지생성시간      int64
응답코드         int64
데이터길이        int64
수집유형        object
DTG정보수       int64
차량코드         int64
차량번호        object
Column1    float64
dtype: object

In [55]:
df["단말ID"].count()

28538

In [56]:
# unique로 중복을 제거한 값을 보고 nunique로 그 개수를 세어본다. 
# ts: trip_start
ts = df["트립시작일"].unique()
ts

array(['2022-11-01 9:12', '2022-11-01 9:33', '2022-11-01 9:44',
       '2022-11-01 10:18', '2022-11-01 12:55', '2022-11-01 15:35',
       '2022-11-01 15:45', '2022-11-01 16:19', '2022-11-01 18:45'],
      dtype=object)

In [57]:
ts[0]

'2022-11-01 9:12'

In [58]:
df["트립시작일"].nunique()

9

In [59]:
df["정보발생일"].unique()

array(['2022-11-01 9:11:48', '2022-11-01 9:11:51', '2022-11-01 9:11:52',
       ..., '2022-11-01 20:21:13', '2022-11-01 20:21:14',
       '2022-11-01 20:21:15'], dtype=object)

In [60]:
df["정보발생일"].nunique()

28536

## 특정 데이터만 모아서 따로 보기

In [61]:
#"트립시작일"이 'ts[0]'에 해당하는 데이터만 가져와서 변수에 담기
#copy()를 해주면 df_ts0 변수에 변화가 생겨도 df 원본은 변하지 않기 때문에 안전하다.
df_ts0 = df[df["트립시작일"] == ts[0]].copy()
df_ts0

,단말ID,차대번호,트립시작일,정보발생일,누적주행거리,일일주행거리,차량속도,RPM,브레이크상태,차량위치X,...,운전자코드,메시지생성일자,메시지생성시간,응답코드,데이터길이,수집유형,DTG정보수,차량코드,차량번호,Column1
0,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:11:48,1045469,0,0,125,1,0,...,9179345,2022-11-01,91245,0,4924,C,60,15,충남72아3043,NaN
1,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:11:51,1045469,0,0,275,0,0,...,9179345,2022-11-01,91245,0,4924,C,60,15,충남72아3043,NaN
2,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:11:52,1045469,0,0,665,0,0,...,9179345,2022-11-01,91245,0,4924,C,60,15,충남72아3043,NaN
3,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:11:53,1045469,0,0,722,0,0,...,9179345,2022-11-01,91245,0,4924,C,60,15,충남72아3043,NaN
4,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:11:54,1045469,0,0,543,0,0,...,9179345,2022-11-01,91245,0,4924,C,60,15,충남72아3043,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:15:27,1045469,0,0,500,0,0,...,9179345,2022-11-01,91528,0,3448,C,42,15,충남72아3043,NaN
218,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:15:28,1045469,0,0,499,0,0,...,9179345,2022-11-01,91528,0,3448,C,42,15,충남72아3043,NaN
219,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:15:29,1045469,0,0,499,0,0,...,9179345,2022-11-01,91528,0,3448,C,42,15,충남72아3043,NaN
220,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:15:30,1045469,0,0,499,0,0,...,9179345,2022-11-01,91528,0,3448,C,42,15,충남72아3043,NaN
221,1229496162,KMJKG18KPGC011086,2022-11-01 9:12,2022-11-01 9:15:31,1045469,0,0,499,0,0,...,9179345,2022-11-01,91528,0,3448,C,42,15,충남72아3043,NaN

In [45]:
for i in range(len(ts)):
    df_ts = df[df["트립시작일"] == ts[i]].copy()
    print(df_ts)

           단말ID               차대번호            트립시작일               정보발생일
0    1229496162  KMJKG18KPGC011086  2022-11-01 9:12  2022-11-01 9:11:48  \
1    1229496162  KMJKG18KPGC011086  2022-11-01 9:12  2022-11-01 9:11:51
2    1229496162  KMJKG18KPGC011086  2022-11-01 9:12  2022-11-01 9:11:52
3    1229496162  KMJKG18KPGC011086  2022-11-01 9:12  2022-11-01 9:11:53
4    1229496162  KMJKG18KPGC011086  2022-11-01 9:12  2022-11-01 9:11:54
..          ...                ...              ...                 ...
217  1229496162  KMJKG18KPGC011086  2022-11-01 9:12  2022-11-01 9:15:27
218  1229496162  KMJKG18KPGC011086  2022-11-01 9:12  2022-11-01 9:15:28
219  1229496162  KMJKG18KPGC011086  2022-11-01 9:12  2022-11-01 9:15:29
220  1229496162  KMJKG18KPGC011086  2022-11-01 9:12  2022-11-01 9:15:30
221  1229496162  KMJKG18KPGC011086  2022-11-01 9:12  2022-11-01 9:15:31

      누적주행거리  일일주행거리  차량속도  RPM  브레이크상태  차량위치X  ...    운전자코드     메시지생성일자
0    1045469       0     0  125       1      0  ...  9179345  2022-11-01  \
1    1045469       0     0  275       0      0  ...  9179345  2022-11-01
2    1045469       0     0  665       0      0  ...  9179345  2022-11-01
3    1045469       0     0  722       0      0  ...  9179345  2022-11-01
4    1045469       0     0  543       0      0  ...  9179345  2022-11-01
..       ...     ...   ...  ...     ...    ...  ...      ...         ...
217  1045469       0     0  500       0      0  ...  9179345  2022-11-01
218  1045469       0     0  499       0      0  ...  9179345  2022-11-01
219  1045469       0     0  499       0      0  ...  9179345  2022-11-01
220  1045469       0     0  499       0      0  ...  9179345  2022-11-01
221  1045469       0     0  499       0      0  ...  9179345  2022-11-01

     메시지생성시간  응답코드  데이터길이  수집유형  DTG정보수  차량코드       차량번호  Column1
0      91245     0   4924     C      60    15  충남72아3043      NaN
1      91245     0   4924     C      60    15  충남72아3043      NaN
2      91245     0   4924     C      60    15  충남72아3043      NaN
3      91245     0   4924     C      60    15  충남72아3043      NaN
4      91245     0   4924     C      60    15  충남72아3043      NaN
..       ...   ...    ...   ...     ...   ...        ...      ...
217    91528     0   3448     C      42    15  충남72아3043      NaN
218    91528     0   3448     C      42    15  충남72아3043      NaN
219    91528     0   3448     C      42    15  충남72아3043      NaN
220    91528     0   3448     C      42    15  충남72아3043      NaN
221    91528     0   3448     C      42    15  충남72아3043      NaN

[222 rows x 32 columns]
           단말ID               차대번호            트립시작일               정보발생일
222  1229496162  KMJKG18KPGC011086  2022-11-01 9:33  2022-11-01 9:33:24  \
223  1229496162  KMJKG18KPGC011086  2022-11-01 9:33  2022-11-01 9:33:26
224  1229496162  KMJKG18KPGC011086  2022-11-01 9:33  2022-11-01 9:33:27
225  1229496162  KMJKG18KPGC011086  2022-11-01 9:33  2022-11-01 9:33:28
226  1229496162  KMJKG18KPGC011086  2022-11-01 9:33  2022-11-01 9:33:29
..          ...                ...              ...                 ...
421  1229496162  KMJKG18KPGC011086  2022-11-01 9:33  2022-11-01 9:36:44
422  1229496162  KMJKG18KPGC011086  2022-11-01 9:33  2022-11-01 9:36:45
423  1229496162  KMJKG18KPGC011086  2022-11-01 9:33  2022-11-01 9:36:46
424  1229496162  KMJKG18KPGC011086  2022-11-01 9:33  2022-11-01 9:36:47
425  1229496162  KMJKG18KPGC011086  2022-11-01 9:33  2022-11-01 9:36:48

      누적주행거리  일일주행거리  차량속도  RPM  브레이크상태  차량위치X  ...    운전자코드     메시지생성일자
222  1045469       0     0    0       1      0  ...  9179345  2022-11-01  \
223  1045469       0     0  159       1      0  ...  9179345  2022-11-01
224  1045469       0     0  342       1      0  ...  9179345  2022-11-01
225  1045469       0     0  765       1      0  ...  9179345  2022-11-01
226  1045469       0     0  666       1      0  ...  9179345  2022-11-01
..       ...     ...   ...  ...     ...    ...  ...      ...         ...
421  1045469       0     0  497       1      0  ...  9179345  2022-11-01
422  1045469       0     0  498       1      0  ...  9179345  2022-11-01
423  1045469       0     0  494       1      0  ...  9179345  2022-11-01
424  1045469       0     0  501       0      0  ...  9179345  2022-11-01
425  1045469       0     0  500       0      0  ...  9179345  2022-11-01

     메시지생성시간  응답코드  데이터길이  수집유형  DTG정보수  차량코드       차량번호  Column1
222    93421     0   4924     C      60    15  충남72아3043      NaN
223    93421     0   4924     C      60    15  충남72아3043      NaN
224    93421     0   4924     C      60    15  충남72아3043      NaN
225    93421     0   4924     C      60    15  충남72아3043      NaN
226    93421     0   4924     C      60    15  충남72아3043      NaN
..       ...   ...    ...   ...     ...   ...        ...      ...
421    93646     0   1972     C      24    15  충남72아3043      NaN
422    93646     0   1972     C      24    15  충남72아3043      NaN
423    93646     0   1972     C      24    15  충남72아3043      NaN
424    93646     0   1972     C      24    15  충남72아3043      NaN
425    93646     0   1972     C      24    15  충남72아3043      NaN

[204 rows x 32 columns]
            단말ID               차대번호            트립시작일                정보발생일
426   1229496162  KMJKG18KPGC011086  2022-11-01 9:44   2022-11-01 9:44:05  \
427   1229496162  KMJKG18KPGC011086  2022-11-01 9:44   2022-11-01 9:44:08
428   1229496162  KMJKG18KPGC011086  2022-11-01 9:44   2022-11-01 9:44:09
429   1229496162  KMJKG18KPGC011086  2022-11-01 9:44   2022-11-01 9:44:10
430   1229496162  KMJKG18KPGC011086  2022-11-01 9:44   2022-11-01 9:44:11
...          ...                ...              ...                  ...
1732  1229496162  KMJKG18KPGC011086  2022-11-01 9:44  2022-11-01 10:05:51
1733  1229496162  KMJKG18KPGC011086  2022-11-01 9:44  2022-11-01 10:05:52
1734  1229496162  KMJKG18KPGC011086  2022-11-01 9:44  2022-11-01 10:05:53
1735  1229496162  KMJKG18KPGC011086  2022-11-01 9:44  2022-11-01 10:05:54
1736  1229496162  KMJKG18KPGC011086  2022-11-01 9:44  2022-11-01 10:05:55

       누적주행거리  일일주행거리  차량속도  RPM  브레이크상태      차량위치X  ...    운전자코드     메시지생성일자
426   1045469       0     0    0       0          0  ...  9179345  2022-11-01  \
427   1045469       0     0    0       0          0  ...  9179345  2022-11-01
428   1045469       0     0    0       0          0  ...  9179345  2022-11-01
429   1045469       0     0    0       0          0  ...  9179345  2022-11-01
430   1045469       0     0    0       0          0  ...  9179345  2022-11-01
...       ...     ...   ...  ...     ...        ...  ...      ...         ...
1732  1045487      17     3  500       1  126458219  ...  9179345  2022-11-01
1733  1045487      17     2  500       1  126458221  ...  9179345  2022-11-01
1734  1045487      17     1  498       1  126458221  ...  9179345  2022-11-01
1735  1045487      17     0  492       1  126458221  ...  9179345  2022-11-01
1736  1045487      17     0  500       1  126458214  ...  9179345  2022-11-01

      메시지생성시간  응답코드  데이터길이  수집유형  DTG정보수  차량코드       차량번호  Column1
426     94502     0   4924     C      60    15  충남72아3043      NaN
427     94502     0   4924     C      60    15  충남72아3043      NaN
428     94502     0   4924     C      60    15  충남72아3043      NaN
429     94502     0   4924     C      60    15  충남72아3043      NaN
430     94502     0   4924     C      60    15  충남72아3043      NaN
...       ...   ...    ...   ...     ...   ...        ...      ...
1732   100555     0   4186     C      51    15  충남72아3043      NaN
1733   100555     0   4186     C      51    15  충남72아3043      NaN
1734   100555     0   4186     C      51    15  충남72아3043      NaN
1735   100555     0   4186     C      51    15  충남72아3043      NaN
1736   100555     0   4186     C      51    15  충남72아3043      NaN

[1311 rows x 32 columns]
            단말ID               차대번호             트립시작일                정보발생일
1737  1229496162  KMJKG18KPGC011086  2022-11-01 10:18  2022-11-01 10:18:25  \
1738  1229496162  KMJKG18KPGC011086  2022-11-01 10:18  2022-11-01 10:18:27
1739  1229496162  KMJKG18KPGC011086  2022-11-01 10:18  2022-11-01 10:18:28
1740  1229496162  KMJKG18KPGC011086  2022-11-01 10:18  2022-11-01 10:18:29
1741  1229496162  KMJKG18KPGC011086  2022-11-01 10:18  2022-11-01 10:18:30
...          ...                ...               ...                  ...
7160  1229496162  KMJKG18KPGC011086  2022-11-01 10:18  2022-11-01 11:48:49
7161  1229496162  KMJKG18KPGC011086  2022-11-01 10:18  2022-11-01 11:48:50
7162  1229496162  KMJKG18KPGC011086  2022-11-01 10:18  2022-11-01 11:48:51
7163  1229496162  KMJKG18KPGC011086  2022-11-01 10:18  2022-11-01 11:48:52
7164  1229496162  KMJKG18KPGC011086  2022-11-01 10:18  2022-11-01 11:48:53

       누적주행거리  일일주행거리  차량속도  RPM  브레이크상태      차량위치X  ...    운전자코드     메시지생성일자
1737  1045487      17     0    0       0          0  ...  9179345  2022-11-01  \
1738  1045487      17     0    0       0          0  ...  9179345  2022-11-01
1739  1045487      17     0  220       0          0  ...  9179345  2022-11-01
1740  1045487      17     0  461       0          0  ...  9179345  2022-11-01
1741  1045487      17     0  845       0          0  ...  9179345  2022-11-01
...       ...     ...   ...  ...     ...        ...  ...      ...         ...
7160  1045597     128     2  499       1  127020287  ...  9179345  2022-11-01
7161  1045597     128     2  499       1  127020280  ...  9179345  2022-11-01
7162  1045597     128     0  499       1  127020275  ...  9179345  2022-11-01
7163  1045597     128     0  491       1  127020273  ...  9179345  2022-11-01
7164  1045597     128     0  506       0  127020269  ...  9179345  2022-11-01

      메시지생성시간  응답코드  데이터길이  수집유형  DTG정보수  차량코드       차량번호  Column1
1737   101924     0   4924     C      60    15  충남72아3043      NaN
1738   101924     0   4924     C      60    15  충남72아3043      NaN
1739   101924     0   4924     C      60    15  충남72아3043      NaN
1740   101924     0   4924     C      60    15  충남72아3043      NaN
1741   101924     0   4924     C      60    15  충남72아3043      NaN
...       ...   ...    ...   ...     ...   ...        ...      ...
7160   114853     0   2300     C      28    15  충남72아3043      NaN
7161   114853     0   2300     C      28    15  충남72아3043      NaN
7162   114853     0   2300     C      28    15  충남72아3043      NaN
7163   114853     0   2300     C      28    15  충남72아3043      NaN
7164   114853     0   2300     C      28    15  충남72아3043      NaN

[5428 rows x 32 columns]
             단말ID               차대번호             트립시작일                정보발생일
7165   1229496162  KMJKG18KPGC011086  2022-11-01 12:55  2022-11-01 12:54:45  \
7166   1229496162  KMJKG18KPGC011086  2022-11-01 12:55  2022-11-01 12:54:47
7167   1229496162  KMJKG18KPGC011086  2022-11-01 12:55  2022-11-01 12:54:48
7168   1229496162  KMJKG18KPGC011086  2022-11-01 12:55  2022-11-01 12:54:49
7169   1229496162  KMJKG18KPGC011086  2022-11-01 12:55  2022-11-01 12:54:50
...           ...                ...               ...                  ...
13278  1229496162  KMJKG18KPGC011086  2022-11-01 12:55  2022-11-01 14:36:39
13279  1229496162  KMJKG18KPGC011086  2022-11-01 12:55  2022-11-01 14:36:40
13280  1229496162  KMJKG18KPGC011086  2022-11-01 12:55  2022-11-01 14:36:41
13281  1229496162  KMJKG18KPGC011086  2022-11-01 12:55  2022-11-01 14:36:42
13282  1229496162  KMJKG18KPGC011086  2022-11-01 12:55  2022-11-01 14:36:43

        누적주행거리  일일주행거리  차량속도  RPM  브레이크상태  차량위치X  ...    운전자코드     메시지생성일자
7165   1045597     128     0    0       0      0  ...  9179345  2022-11-01  \
7166   1045597     128     0  206       0      0  ...  9179345  2022-11-01
7167   1045597     128     0  540       0      0  ...  9179345  2022-11-01
7168   1045597     128     0  837       0      0  ...  9179345  2022-11-01
7169   1045597     128     0  614       0      0  ...  9179345  2022-11-01
...        ...     ...   ...  ...     ...    ...  ...      ...         ...
13278  1045707     238     0  501       0      0  ...  9179345  2022-11-01
13279  1045707     238     0  506       0      0  ...  9179345  2022-11-01
13280  1045707     238     0  503       0      0  ...  9179345  2022-11-01
13281  1045707     238     0  500       0      0  ...  9179345  2022-11-01
13282  1045707     238     0  499       0      0  ...  9179345  2022-11-01

       메시지생성시간  응답코드  데이터길이  수집유형  DTG정보수  차량코드       차량번호  Column1
7165    125544     0   4924     C      60    15  충남72아3043      NaN
7166    125544     0   4924     C      60    15  충남72아3043      NaN
7167    125544     0   4924     C      60    15  충남72아3043      NaN
7168    125544     0   4924     C      60    15  충남72아3043      NaN
7169    125544     0   4924     C      60    15  충남72아3043      NaN
...        ...   ...    ...   ...     ...   ...        ...      ...
13278   143643     0   4760     C      58    15  충남72아3043      NaN
13279   143643     0   4760     C      58    15  충남72아3043      NaN
13280   143643     0   4760     C      58    15  충남72아3043      NaN
13281   143643     0   4760     C      58    15  충남72아3043      NaN
13282   143643     0   4760     C      58    15  충남72아3043      NaN

[6118 rows x 32 columns]
             단말ID               차대번호             트립시작일                정보발생일
13283  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:09  \
13284  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:11
13285  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:12
13286  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:13
13287  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:14
13288  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:15
13289  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:16
13290  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:17
13291  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:18
13292  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:19
13293  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:20
13294  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:21
13295  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:22
13296  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:23
13297  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:24
13298  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:25
13299  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:26
13300  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:27
13301  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:28
13302  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:29
13303  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:30
13304  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:31
13305  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:32
13306  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:33
13307  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:34
13308  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:35
13309  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:36
13310  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:37
13311  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:38
13312  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:39
13313  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:40
13314  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:41
13315  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:42
13316  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:43
13317  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:44
13318  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:45
13319  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:46
13320  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:47
13321  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:48
13322  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:49
13323  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:50
13324  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:51
13325  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:52
13326  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:53
13327  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:54
13328  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:55
13329  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:56
13330  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:57
13331  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:58
13332  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:35:59
13333  1229496162  KMJKG18KPGC011086  2022-11-01 15:35  2022-11-01 15:36:00

        누적주행거리  일일주행거리  차량속도  RPM  브레이크상태  차량위치X  ...    운전자코드     메시지생성일자
13283  1045707     238     0    0       0      0  ...  9179345  2022-11-01  \
13284  1045707     238     0  113       0      0  ...  9179345  2022-11-01
13285  1045707     238     0  314       0      0  ...  9179345  2022-11-01
13286  1045707     238     0  722       1      0  ...  9179345  2022-11-01
13287  1045707     238     0  755       1      0  ...  9179345  2022-11-01
13288  1045707     238     0  552       1      0  ...  9179345  2022-11-01
13289  1045707     238     0  489       1      0  ...  9179345  2022-11-01
13290  1045707     238     0  488       1      0  ...  9179345  2022-11-01
13291  1045707     238     0  499       1      0  ...  9179345  2022-11-01
13292  1045707     238     0  503       1      0  ...  9179345  2022-11-01
13293  1045707     238     0  499       0      0  ...  9179345  2022-11-01
13294  1045707     238     0  499       0      0  ...  9179345  2022-11-01
13295  1045707     238     0  534       0      0  ...  9179345  2022-11-01
13296  1045707     238     0  463       0      0  ...  9179345  2022-11-01
13297  1045707     238     1  454       0      0  ...  9179345  2022-11-01
13298  1045707     238     3  447       0      0  ...  9179345  2022-11-01
13299  1045707     238     5  451       0      0  ...  9179345  2022-11-01
13300  1045707     238     7  607       1      0  ...  9179345  2022-11-01
13301  1045707     238     8  585       0      0  ...  9179345  2022-11-01
13302  1045707     238     8  513       1      0  ...  9179345  2022-11-01
13303  1045707     238     7  489       0      0  ...  9179345  2022-11-01
13304  1045707     238     7  493       0      0  ...  9179345  2022-11-01
13305  1045707     238     7  471       0      0  ...  9179345  2022-11-01
13306  1045707     238     7  488       0      0  ...  9179345  2022-11-01
13307  1045707     238     7  511       0      0  ...  9179345  2022-11-01
13308  1045707     238     8  543       1      0  ...  9179345  2022-11-01
13309  1045707     238     8  507       0      0  ...  9179345  2022-11-01
13310  1045707     238     8  495       0      0  ...  9179345  2022-11-01
13311  1045707     238     8  493       0      0  ...  9179345  2022-11-01
13312  1045707     238     7  497       0      0  ...  9179345  2022-11-01
13313  1045707     238     7  500       0      0  ...  9179345  2022-11-01
13314  1045707     238     6  503       0      0  ...  9179345  2022-11-01
13315  1045707     238     6  482       0      0  ...  9179345  2022-11-01
13316  1045707     238     6  466       0      0  ...  9179345  2022-11-01
13317  1045707     238     6  456       0      0  ...  9179345  2022-11-01
13318  1045707     238     7  487       0      0  ...  9179345  2022-11-01
13319  1045707     238     8  518       0      0  ...  9179345  2022-11-01

             단말ID               차대번호             트립시작일                정보발생일
22770  1229496162  KMJKG18KPGC011086  2022-11-01 18:45  2022-11-01 18:45:06  \
22771  1229496162  KMJKG18KPGC011086  2022-11-01 18:45  2022-11-01 18:45:09
22772  1229496162  KMJKG18KPGC011086  2022-11-01 18:45  2022-11-01 18:45:10
22773  1229496162  KMJKG18KPGC011086  2022-11-01 18:45  2022-11-01 18:45:11
22774  1229496162  KMJKG18KPGC011086  2022-11-01 18:45  2022-11-01 18:45:12
...           ...                ...               ...                  ...
28533  1229496162  KMJKG18KPGC011086  2022-11-01 18:45  2022-11-01 20:21:11
28534  1229496162  KMJKG18KPGC011086  2022-11-01 18:45  2022-11-01 20:21:12
28535  1229496162  KMJKG18KPGC011086  2022-11-01 18:45  2022-11-01 20:21:13
28536  1229496162  KMJKG18KPGC011086  2022-11-01 18:45  2022-11-01 20:21:14
28537  1229496162  KMJKG18KPGC011086  2022-11-01 18:45  2022-11-01 20:21:15

        누적주행거리  일일주행거리  차량속도  RPM  브레이크상태  차량위치X  ...    운전자코드     메시지생성일자
22770  1045835     366     0    0       1      0  ...  9179345  2022-11-01  \
22771  1045835     366     0  202       1      0  ...  9179345  2022-11-01
22772  1045835     366     0  414       1      0  ...  9179345  2022-11-01
22773  1045835     366     0  840       1      0  ...  9179345  2022-11-01
22774  1045835     366     0  648       0      0  ...  9179345  2022-11-01
...        ...     ...   ...  ...     ...    ...  ...      ...         ...
28533  1045946     476     0  509       0      0  ...  9179345  2022-11-01
28534  1045946     476     0  519       0      0  ...  9179345  2022-11-01
28535  1045946     476     0  507       0      0  ...  9179345  2022-11-01
28536  1045946     476     0  499       0      0  ...  9179345  2022-11-01
28537  1045946     476     0  496       0      0  ...  9179345  2022-11-01

       메시지생성시간  응답코드  데이터길이  수집유형  DTG정보수  차량코드       차량번호  Column1
22770   184606     0   4924     C      60    15  충남72아3043      NaN
22771   184606     0   4924     C      60    15  충남72아3043      NaN
22772   184606     0   4924     C      60    15  충남72아3043      NaN
22773   184606     0   4924     C      60    15  충남72아3043      NaN
22774   184606     0   4924     C      60    15  충남72아3043      NaN
...        ...   ...    ...   ...     ...   ...        ...      ...
28533   202115     0    660     C       8    15  충남72아3043      NaN
28534   202115     0    660     C       8    15  충남72아3043      NaN
28535   202115     0    660     C       8    15  충남72아3043      NaN
28536   202115     0    660     C       8    15  충남72아3043      NaN
28537   202115     0    660     C       8    15  충남72아3043      NaN

[5768 rows x 32 columns]

In [30]:
len(ts)

9

In [62]:
# 출발일시: 트립시작일
# 도착일시: 정보발생일(마지막 값)
# 운전자명:
# DTG 상태: 
# 운행 시간: 정보발생일(마지막 값)-트립시작일
# 운행 거리: 누적주행거리(마지막 값) - 누적주행거리(첫번째 값)
# 최고 속도: 차량속도(max)
# 평균 속도: 차량속도(average)
# 최고 RPM: max(RPM)
# 평균 RPM: average(RPM)
# 전압정보: 배터리 전압 (min~max)
# 과속시간: 과속의 기준이 뭔가요?
# 누적주행거리: 누적주행거리(마지막 값)

In [64]:
df_ts8 = df[df["트립시작일"] == ts[8]].copy()
df_ts8

,단말ID,차대번호,트립시작일,정보발생일,누적주행거리,일일주행거리,차량속도,RPM,브레이크상태,차량위치X,...,운전자코드,메시지생성일자,메시지생성시간,응답코드,데이터길이,수집유형,DTG정보수,차량코드,차량번호,Column1
22770,1229496162,KMJKG18KPGC011086,2022-11-01 18:45,2022-11-01 18:45:06,1045835,366,0,0,1,0,...,9179345,2022-11-01,184606,0,4924,C,60,15,충남72아3043,NaN
22771,1229496162,KMJKG18KPGC011086,2022-11-01 18:45,2022-11-01 18:45:09,1045835,366,0,202,1,0,...,9179345,2022-11-01,184606,0,4924,C,60,15,충남72아3043,NaN
22772,1229496162,KMJKG18KPGC011086,2022-11-01 18:45,2022-11-01 18:45:10,1045835,366,0,414,1,0,...,9179345,2022-11-01,184606,0,4924,C,60,15,충남72아3043,NaN
22773,1229496162,KMJKG18KPGC011086,2022-11-01 18:45,2022-11-01 18:45:11,1045835,366,0,840,1,0,...,9179345,2022-11-01,184606,0,4924,C,60,15,충남72아3043,NaN
22774,1229496162,KMJKG18KPGC011086,2022-11-01 18:45,2022-11-01 18:45:12,1045835,366,0,648,0,0,...,9179345,2022-11-01,184606,0,4924,C,60,15,충남72아3043,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28533,1229496162,KMJKG18KPGC011086,2022-11-01 18:45,2022-11-01 20:21:11,1045946,476,0,509,0,0,...,9179345,2022-11-01,202115,0,660,C,8,15,충남72아3043,NaN
28534,1229496162,KMJKG18KPGC011086,2022-11-01 18:45,2022-11-01 20:21:12,1045946,476,0,519,0,0,...,9179345,2022-11-01,202115,0,660,C,8,15,충남72아3043,NaN
28535,1229496162,KMJKG18KPGC011086,2022-11-01 18:45,2022-11-01 20:21:13,1045946,476,0,507,0,0,...,9179345,2022-11-01,202115,0,660,C,8,15,충남72아3043,NaN
28536,1229496162,KMJKG18KPGC011086,2022-11-01 18:45,2022-11-01 20:21:14,1045946,476,0,499,0,0,...,9179345,2022-11-01,202115,0,660,C,8,15,충남72아3043,NaN
28537,1229496162,KMJKG18KPGC011086,2022-11-01 18:45,2022-11-01 20:21:15,1045946,476,0,496,0,0,...,9179345,2022-11-01,202115,0,660,C,8,15,충남72아3043,NaN